In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv("weather.csv")
df.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MinTemp        366 non-null    float64
 1   MaxTemp        366 non-null    float64
 2   Rainfall       366 non-null    float64
 3   Evaporation    366 non-null    float64
 4   Sunshine       363 non-null    float64
 5   WindGustDir    363 non-null    object
 6   WindGustSpeed  364 non-null    float64
 7   WindDir9am     335 non-null    object
 8   WindDir3pm     365 non-null    object
 9   WindSpeed9am   359 non-null    float64
 10  WindSpeed3pm   366 non-null    int64
 11  Humidity9am    366 non-null    int64
 12  Humidity3pm    366 non-null    int64
 13  Pressure9am    366 non-null    float64
 14  Pressure3pm    366 non-null    float64
 15  Cloud9am       366 non-null    int64
 16  Cloud3pm       366 non-null    int64
 17  Temp9am        366 non-null    float64
 18  Temp3pm        366 non-null    float64
 19  RainToday      366 non-null    object
 20  RISK_MM        366 non-null    float64
 21  RainTomorrow   366 non-null    object
dtypes: float64(12), int64(5), object(5)
memory usage: 63.0+ KB

In [3]:
df.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,366.000000,366.000000,366.000000,366.000000,363.000000,364.000000,359.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,7.265574,20.550273,1.428415,4.521858,7.909366,39.840659,9.651811,17.986339,72.035519,44.519126,1019.709016,1016.810383,3.890710,4.024590,12.358470,19.230874,1.428415
std,6.025800,6.690516,4.225800,2.669383,3.481517,13.059807,7.951929,8.856997,13.137058,16.850947,6.686212,6.469422,2.956131,2.666268,5.630832,6.640346,4.225800
min,-5.300000,7.600000,0.000000,0.200000,0.000000,13.000000,0.000000,0.000000,36.000000,13.000000,996.500000,996.800000,0.000000,0.000000,0.100000,5.100000,0.000000
25%,2.300000,15.025000,0.000000,2.200000,5.950000,31.000000,6.000000,11.000000,64.000000,32.250000,1015.350000,1012.800000,1.000000,1.000000,7.625000,14.150000,0.000000
50%,7.450000,19.650000,0.000000,4.200000,8.600000,39.000000,7.000000,17.000000,72.000000,43.000000,1020.150000,1017.400000,3.500000,4.000000,12.550000,18.550000,0.000000
75%,12.500000,25.500000,0.200000,6.400000,10.500000,46.000000,13.000000,24.000000,81.000000,55.000000,1024.475000,1021.475000,7.000000,7.000000,17.000000,24.000000,0.200000
max,20.900000,35.800000,39.800000,13.800000,13.600000,98.000000,41.000000,52.000000,99.000000,96.000000,1035.700000,1033.200000,8.000000,8.000000,24.700000,34.500000,39.800000

In [4]:
df.isnull().sum()

MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          3
WindGustDir       3
WindGustSpeed     2
WindDir9am       31
WindDir3pm        1
WindSpeed9am      7
WindSpeed3pm      0
Humidity9am       0
Humidity3pm       0
Pressure9am       0
Pressure3pm       0
Cloud9am          0
Cloud3pm          0
Temp9am           0
Temp3pm           0
RainToday         0
RISK_MM           0
RainTomorrow      0
dtype: int64

In [5]:
data=df.dropna()
data

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [6]:
data.isnull().sum()

MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RISK_MM          0
RainTomorrow     0
dtype: int64

In [7]:
data.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [8]:
data

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [9]:
data.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000,328.000000
mean,7.742988,20.897561,1.440854,4.702439,8.014939,40.396341,10.414634,18.185976,71.100610,44.003049,1019.350000,1016.530793,3.905488,4.000000,12.815549,19.556402,1.422561
std,5.945199,6.707310,4.289427,2.681183,3.506646,13.132176,7.811544,8.926759,12.983367,16.605975,6.715244,6.469774,2.974957,2.652101,5.542521,6.644311,4.234023
min,-5.300000,7.600000,0.000000,0.200000,0.000000,13.000000,2.000000,4.000000,36.000000,13.000000,996.500000,996.800000,0.000000,0.000000,0.100000,5.100000,0.000000
25%,2.850000,15.500000,0.000000,2.550000,6.000000,31.000000,6.000000,11.000000,63.000000,32.000000,1014.800000,1012.400000,1.000000,1.000000,8.175000,14.500000,0.000000
50%,7.900000,20.400000,0.000000,4.400000,8.750000,39.000000,7.000000,17.000000,71.000000,42.500000,1019.750000,1016.900000,4.000000,4.000000,13.500000,18.850000,0.000000
75%,12.800000,25.800000,0.200000,6.600000,10.700000,46.000000,13.000000,24.000000,80.000000,54.000000,1024.300000,1021.125000,7.000000,7.000000,17.200000,24.225000,0.200000
max,20.900000,35.800000,39.800000,13.800000,13.600000,98.000000,41.000000,52.000000,99.000000,93.000000,1035.700000,1033.200000,8.000000,8.000000,24.700000,34.500000,39.800000

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 328 entries, 0 to 365
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MinTemp        328 non-null    float64
 1   MaxTemp        328 non-null    float64
 2   Rainfall       328 non-null    float64
 3   Evaporation    328 non-null    float64
 4   Sunshine       328 non-null    float64
 5   WindGustDir    328 non-null    object
 6   WindGustSpeed  328 non-null    float64
 7   WindDir9am     328 non-null    object
 8   WindDir3pm     328 non-null    object
 9   WindSpeed9am   328 non-null    float64
 10  WindSpeed3pm   328 non-null    int64
 11  Humidity9am    328 non-null    int64
 12  Humidity3pm    328 non-null    int64
 13  Pressure9am    328 non-null    float64
 14  Pressure3pm    328 non-null    float64
 15  Cloud9am       328 non-null    int64
 16  Cloud3pm       328 non-null    int64
 17  Temp9am        328 non-null    float64
 18  Temp3pm        328 non-null    float64
 19  RainToday      328 non-null    object
 20  RISK_MM        328 non-null    float64
 21  RainTomorrow   328 non-null    object
dtypes: float64(12), int64(5), object(5)
memory usage: 58.9+ KB

In [13]:
pip install nb2xls

Collecting nb2xls
  Downloading nb2xls-0.1.6.tar.gz (10 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: nbconvert>=5.0.0 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nb2xls) (7.14.0)
Collecting xlsxwriter>=1.1.0 (from nb2xls)
  Obtaining dependency information for xlsxwriter>=1.1.0 from https://files.pythonhosted.org/packages/f7/3e/05ba2194cd5073602422859c949a4f21310a3c49bf8dccde9e03d4522b11/XlsxWriter-3.1.9-py3-none-any.whl.metadata
  Downloading XlsxWriter-3.1.9-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: beautifulsoup4>=4.6.0 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nb2xls) (4.12.2)
Collecting pypng>=0.0.18 (from nb2xls)
  Downloading pypng-0.20220715.0-py3-none-any.whl (58 kB)
     ---------------------------------------- 0.0/58.1 kB ? eta -:--:--
     ---------------------------------------- 0.0/58.1 kB ? eta -:--:--
     -------------------- ----------------- 30.7/58.1 kB 640.0 kB/s eta 0:00:01
     -------------------- ----------------- 30.7/58.1 kB 640.0 kB/s eta 0:00:01
     --------------------------------- ---- 51.2/58.1 kB 372.4 kB/s eta 0:00:01
     -------------------------------------- 58.1/58.1 kB 339.1 kB/s eta 0:00:00
Requirement already satisfied: mistune>=0.8 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nb2xls) (3.0.2)
Requirement already satisfied: pandas in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nb2xls) (2.1.4)
Requirement already satisfied: numpy in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nb2xls) (1.26.3)
Requirement already satisfied: soupsieve>1.2 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from beautifulsoup4>=4.6.0->nb2xls) (2.5)
Requirement already satisfied: bleach!=5.0.0 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (6.1.0)
Requirement already satisfied: defusedxml in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (0.7.1)
Requirement already satisfied: jinja2>=3.0 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (3.1.2)
Requirement already satisfied: jupyter-core>=4.7 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (5.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (2.1.3)
Requirement already satisfied: nbclient>=0.5.0 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (0.9.0)
Requirement already satisfied: nbformat>=5.7 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (5.9.2)
Requirement already satisfied: packaging in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (23.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (1.5.0)
Requirement already satisfied: pygments>=2.4.1 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (2.17.2)
Requirement already satisfied: tinycss2 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (1.2.1)
Requirement already satisfied: traitlets>=5.1 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbconvert>=5.0.0->nb2xls) (5.14.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from pandas->nb2xls) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from pandas->nb2xls) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from pandas->nb2xls) (2023.4)
Requirement already satisfied: six>=1.9.0 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from bleach!=5.0.0->nbconvert>=5.0.0->nb2xls) (1.16.0)
Requirement already satisfied: webencodings in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from bleach!=5.0.0->nbconvert>=5.0.0->nb2xls) (0.5.1)
Requirement already satisfied: platformdirs>=2.5 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from jupyter-core>=4.7->nbconvert>=5.0.0->nb2xls) (4.1.0)
Requirement already satisfied: pywin32>=300 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from jupyter-core>=4.7->nbconvert>=5.0.0->nb2xls) (306)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbclient>=0.5.0->nbconvert>=5.0.0->nb2xls) (8.6.0)
Requirement already satisfied: fastjsonschema in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbformat>=5.7->nbconvert>=5.0.0->nb2xls) (2.19.1)
Requirement already satisfied: jsonschema>=2.6 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from nbformat>=5.7->nbconvert>=5.0.0->nb2xls) (4.20.0)
Requirement already satisfied: attrs>=22.2.0 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=5.0.0->nb2xls) (23.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=5.0.0->nb2xls) (2023.12.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=5.0.0->nb2xls) (0.32.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert>=5.0.0->nb2xls) (0.16.2)
Requirement already satisfied: pyzmq>=23.0 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=5.0.0->nb2xls) (25.1.2)
Requirement already satisfied: tornado>=6.2 in c:\users\bholi kumari\appdata\local\programs\python\python312\lib\site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert>=5.0.0->nb2xls) (6.4)
Downloading XlsxWriter-3.1.9-py3-none-any.whl (154 kB)
   ---------------------------------------- 0.0/154.8 kB ? eta -:--:--
   ----------------------- ---------------- 92.2/154.8 kB 2.6 MB/s eta 0:00:01
   ----------------------- ---------------- 92.2/154.8 kB 2.6 MB/s eta 0:00:01
   ---------------------------------------  153.6/154.8 kB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 154.8/154.8 kB 1.2 MB/s eta 0:00:00
Building wheels for collected packages: nb2xls
  Building wheel for nb2xls (pyproject.toml): started
  Building wheel for nb2xls (pyproject.toml): finished with status 'done'
  Created wheel for nb2xls: filename=nb2xls-0.1.6-py3-none-any.whl size=9893 sha256=7057a2ab04161166b9fb7b7f87e7ca9255251537554e78aa59e42b95971d969a
  Stored in directory: c:\users\bholi kumari\appdata\local\pip\cache\wheels\b0\b4\fa\22d426fb70ac4b338ae68e1ff2b9c77b9528d857a7d5fb0814
Successfully built nb2xls
Installing collected packages: pypng, xlsxwriter, nb2xls
Successfully installed nb2xls-0.1.6 pypng-0.20220715.0 xlsxwriter-3.1.9
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
     - -------------------------------------- 10.2/250.0 kB ? eta -:--:--
     ------ ------------------------------ 41.0/250.0 kB 330.3 kB/s eta 0:00:01
     ------ ------------------------------ 41.0/250.0 kB 330.3 kB/s eta 0:00:01
     ------------ ------------------------ 81.9/250.0 kB 353.1 kB/s eta 0:00:01
     ------------ ------------------------ 81.9/250.0 kB 353.1 kB/s eta 0:00:01
     ---------------- ------------------- 112.6/250.0 kB 345.9 kB/s eta 0:00:01
     ---------------- ------------------- 112.6/250.0 kB 345.9 kB/s eta 0:00:01
     ----------------- ------------------ 122.9/250.0 kB 288.8 kB/s eta 0:00:01
     ----------------- ------------------ 122.9/250.0 kB 288.8 kB/s eta 0:00:01
     ------------------------- ---------- 174.1/250.0 kB 327.7 kB/s eta 0:00:01
     ------------------------- ---------- 174.1/250.0 kB 327.7 kB/s eta 0:00:01
     ------------------------- ---------- 174.1/250.0 kB 327.7 kB/s eta 0:00:01
     ------------------------- ---------- 174.1/250.0 kB 327.7 kB/s eta 0:00:01
     ------------------------- ---------- 174.1/250.0 kB 327.7 kB/s eta 0:00:01
     ------------------------- ---------- 174.1/250.0 kB 327.7 kB/s eta 0:00:01
     ------------------------- ---------- 174.1/250.0 kB 327.7 kB/s eta 0:00:01
     ----------------------------- ------ 204.8/250.0 kB 244.4 kB/s eta 0:00:01
     ----------------------------- ------ 204.8/250.0 kB 244.4 kB/s eta 0:00:01
     ----------------------------- ------ 204.8/250.0 kB 244.4 kB/s eta 0:00:01
     -------------------------------- --- 225.3/250.0 kB 237.3 kB/s eta 0:00:01
     -------------------------------- --- 225.3/250.0 kB 237.3 kB/s eta 0:00:01
     -----------------------------------  245.8/250.0 kB 235.5 kB/s eta 0:00:01
     ------------------------------------ 250.0/250.0 kB 229.2 kB/s eta 0:00:00
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [21]:

data.to_excel(r'C:\Users\BHOLI KUMARI\Desktop\python work\export_dataframe.xlsx',index=False)